apiVersion: v1
kind: Service
metadata:
  name: angular-boilerplate-service
spec:
  selector:
    app: angular-boilerplate

  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  

